# Pandas challenges
You may have noticed that all the way along we've been giving you links to documentation to explore the attributes, functions, and methods further. This is an important part of coding: nobody has everything memorised, but we are all experts at Googling the information we need quickly.
 
In this notebook we've included a couple of challenges that require methods we haven't taught you - this is a purposeful move to start your path to Google glory. Search around, read pandas docs, stack overflow, medium, and anywhere else you find information. 
 
If you're totally stuck feel free to ask your "colleagues" (fellow students), your instructor, or one of our junior instructors. Most of the time though, we'll have taught you the answer in one of the previous notebooks, please check back in them too. They will be a great source of information throughout this bootcamp.

In [ ]:
import pandas as pd

###### **Exercise 1:**
read the `vehicles.csv` dataframe and store it in a variable called `cars`:

In [ ]:
# vehicles.csv 'https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing'

# your code here
#import pandas as pd
#path = 'https://drive.google.com/uc?export=download&id=%27+url.split(%27/%27)[-2]
#cars = pd.read_csv(path)
#cars = pd.read_csv('https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing')
#print(cars)

url = 'https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing' # vehicles.csv
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
cars = pd.read_csv(path)
print(cars)

                   Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5
1            AM General     FJ8c Post Office  1984                  4.2
2            AM General  Post Office DJ5 2WD  1985                  2.5
3            AM General  Post Office DJ8 2WD  1985                  4.2
4      ASC Incorporated                  GNX  1987                  3.8
...                 ...                  ...   ...                  ...
35947             smart         fortwo coupe  2013                  1.0
35948             smart         fortwo coupe  2014                  1.0
35949             smart         fortwo coupe  2015                  1.0
35950             smart         fortwo coupe  2016                  0.9
35951             smart         fortwo coupe  2016                  0.9

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive
1            6.0  Automatic 3-spd     2-Wheel Drive
2            4.0  Automatic 3-spd  Rear-Wheel Drive
3            6.0  Automatic 3-spd  Rear-Wheel Drive
4            6.0  Automatic 4-spd  Rear-Wheel Drive
...          ...              ...               ...
35947        3.0        Auto(AM5)  Rear-Wheel Drive
35948        3.0        Auto(AM5)  Rear-Wheel Drive
35949        3.0        Auto(AM5)  Rear-Wheel Drive
35950        3.0        Auto(AM6)  Rear-Wheel Drive
35951        3.0     Manual 5-spd  Rear-Wheel Drive

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18
1      Special Purpose Vehicle 2WD   Regular          25.354615        13
2      Special Purpose Vehicle 2WD   Regular          20.600625        16
3      Special Purpose Vehicle 2WD   Regular          25.354615        13
4                     Midsize Cars   Premium          20.600625        14
...                            ...       ...                ...       ...
35947                  Two Seaters   Premium           9.155833        34
35948                  Two Seaters   Premium           9.155833        34
35949                  Two Seaters   Premium           9.155833        34
35950                  Two Seaters   Premium           9.155833        34
35951                  Two Seaters   Premium           9.417429        32

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year
0               17            17               522.764706            1950
1               13            13               683.615385            2550
2               17            16               555.437500            2100
3               13            13               683.615385            2550
4               21            16               555.437500            2550
...            ...           ...                      ...             ...
35947           38            36               244.000000            1100
35948           38            36               243.000000            1100
35949           38            36               244.000000            1100
35950           39            36               246.000000            1100
35951           39            35               255.000000            1150

[35952 rows x 15 columns]

###### **Exercise 2:**
how many rows and columns are there?

In [ ]:
# your code here
#rows_column = cars.shape
print(cars.shape)

(35952, 15)

###### **Exercise 3:**
what are the data types of the columns? Are there missing values?

In [ ]:
# your code here
#data_type = cars.dtype()
#print(data_type)

null_value_check = cars.info()
#print(cars.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

###### **Exercise 4:**
what are the ranges / distributions of the numerical columns?

In [ ]:
# your code here
#range = cars.hist(bins=4)
cars.describe()

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952.00000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
mean,2000.71640,3.338493,5.765076,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,10.08529,1.359395,1.755268,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,1984.00000,0.600000,2.000000,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,1991.00000,2.200000,4.000000,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,2001.00000,3.000000,6.000000,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,2010.00000,4.300000,6.000000,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,2017.00000,8.400000,16.000000,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

###### **Exercise 5:**
what are the value counts of the `Fuel Type` column?

In [ ]:
# your code here
#import pandas as pd
#cars = pd.read_csv('https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing')
#print(cars["Year"].value_counts())
#print(cars['Fuel Type'].value_counts())


cars["Fuel Type"].value_counts()

Regular                        23587
Premium                         9921
Gasoline or E85                 1195
Diesel                           911
Premium or E85                   121
Midgrade                          74
CNG                               60
Premium and Electricity           20
Gasoline or natural gas           20
Premium Gas or Electricity        17
Regular Gas and Electricity       16
Gasoline or propane                8
Regular Gas or Electricity         2
Name: Fuel Type, dtype: int64

###### **Exercise 6:**
drop the column "Combined MPG"

In [ ]:
# your code here
cars.drop(columns=['Combined MPG'])

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,255.000000,1150

###### **Exercise 7:**
change the column names so that there are no names with spaces or weird special characters:

In [ ]:
# your code here
cars = cars.rename(columns={'Engine Displacement': 'EngineDisplacement', 'Fuel Type':'FuelType','Vehicle Class': 'VehicleClass', 'Fuel Barrels/Year':'FuelBarrelsPerYear', 'City MPG':'CityMPG' ,'Highway MPG':'HighwayMPG' , 'Combined MPG':'CombinedMPG', 'CO2 Emission Grams/Mile':'CO2EmissionGramsPerMile', 'Fuel Cost/Year':'FuelCostPerYear'})
cars.head()
#cars.columns = cars.columns.str.replace(' ', '_')
#cars.columns = cars.columns.str.replace('/','_')

,Make,Model,Year,EngineDisplacement,Cylinders,Transmission,Drivetrain,VehicleClass,FuelType,FuelBarrelsPerYear,CityMPG,HighwayMPG,CombinedMPG,CO2EmissionGramsPerMile,FuelCostPerYear
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

###### **Exercise 8:**
what brand has the most cars?

In [ ]:
# your code here
occur = cars.groupby(['Make']).size()
#print(max(occur))
#cars["Make"].value_counts()

###### **Exercise 9:**
what brand has the worse CO2 Emissions on average?

In [ ]:
# your code here
#groupbybrands = cars.groupby(['Make'])
#meanbybrands = groupbybrands["CO2EmissionGramsPerMile"].mean()
#maxco2emission = 
## your code here
#cars.groupby("CO2_Emission_Gram_per_Mile").max().tail(3)

cars.groupby("Make").CO2EmissionGramsPerMile.mean().sort_values(ascending=False)

Make
Vector                                1049.159722
Superior Coaches Div E.p. Dutton       888.700000
S and S Coach Company  E.p. Dutton     888.700000
Bugatti                                873.062500
Laforza Automobile Inc                 807.909091
                                         ...
MINI                                   313.716862
Daihatsu                               310.188060
Fiat                                   304.666560
smart                                  247.030556
Fisker                                 169.000000
Name: CO2EmissionGramsPerMile, Length: 127, dtype: float64

###### **Exercise 10:**
did cars consume more gas in the eighties?

In [ ]:
# your code here
cars.groupby("Year").FuelBarrelsPerYear.mean()

#cars[cars.Year.isin(['1984','1981','1982','1983','1980','1985','1986','1987','1988','1989'])]
 
Eightys = cars[(cars.Year == 1984) | (cars.Year == 1985) | (cars.Year == 1986) | (cars.Year == 1987)| (cars.Year == 1988)]
Ninties = cars[(cars.Year == 1990) | (cars.Year == 1991)|(cars.Year == 1992) | (cars.Year == 1993)|(cars.Year == 1994) | (cars.Year == 1995)|(cars.Year == 1996) | (cars.Year == 1997)|(cars.Year == 1999)]
twothousands = cars[(cars.Year == 2000) | (cars.Year == 2001) | (cars.Year == 2002) | (cars.Year == 2003)| (cars.Year == 2004) |(cars.Year == 2005) | (cars.Year == 2006) | (cars.Year == 2007) | (cars.Year == 2008)| (cars.Year == 2009)]
twotens = cars[(cars.Year == 2010) | (cars.Year == 2011) | (cars.Year == 2012) | (cars.Year == 2013)| (cars.Year == 2014) |(cars.Year == 2015) | (cars.Year == 2016) | (cars.Year == 2017)]

print(Eightys.FuelBarrelsPerYear.mean())
print(Ninties.FuelBarrelsPerYear.mean())
print(twothousands.FuelBarrelsPerYear.mean())
print(twotens.FuelBarrelsPerYear.mean())

#year_points = [1980, 1990, 2000, 2010,2020]
#cars['decade'] = pd.cut(x = cars['Year'], bins=year_points, labels=[u'80s', u'90s', u'00s', u'10s'])
#cars_decade = cars.groupby('decade')
#cars_decade.head()
#print(cars_decade["Fuel Cost/Year"].mean())
  

#make a new column decade
#cars['Decade'] = (cars['Year'] // 10) * 10
#cars.groupby('Decade').Fuel_Barrels_per_Year.mean()
# Decade 1980 - 1989 has with 18.55 the highest average
#gasEighties = cars.query('Year > 1980 & Year < 1989').mean()
#gasEighties.Fuel_Barrels_per_Year

18.564032974319936
18.33843802923167
17.962476690298235
15.778968389498

###### **Exercise 11:**
group cars by fuel type and aggregate them by the following criteria: 

- The maximum number cylinders
- The oldest year
- The average Miles Per Gallon in the city

In [ ]:
# your code here
cars_group = cars.groupby(['FuelType'])
cars_group["Cylinders"].max()
cars_group['Year'].min()
cars_group['CityMPG'].mean()

##Using groupby('').aggregate
#Fuel_Type_Aggregates = cars.groupby("Fuel_Type").aggregate({'Cylinders':'max', 'Year':'min', 'City_MPG':'mean'})
#print(Fuel_Type_Aggregates)

FuelType
CNG                            15.966667
Diesel                         21.173436
Gasoline or E85                15.347280
Gasoline or natural gas        13.700000
Gasoline or propane            12.000000
Midgrade                       14.851351
Premium                        16.793166
Premium Gas or Electricity     30.705882
Premium and Electricity        24.900000
Premium or E85                 17.305785
Regular                        17.970195
Regular Gas and Electricity    43.125000
Regular Gas or Electricity     43.000000
Name: CityMPG, dtype: float64

###### **Exercise 12:**
read the `car_brands.csv` data:

In [ ]:
# car_brands.csv 'https://drive.google.com/file/d/1jLSArDeSsySULKiRtMNV3V3RKuWAUKbD/view?usp=sharing'
#url = 'https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing' # vehicles.csv
#path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
#cars = pd.read_csv(path)
#print(cars)

# your code here
url1 = 'https://drive.google.com/file/d/1jLSArDeSsySULKiRtMNV3V3RKuWAUKbD/view?usp=sharing'
path1 = 'https://drive.google.com/file/d/1jLSArDeSsySULKiRtMNV3V3RKuWAUKbD/view?usp=sharing'+url1.split('/')[-2]
CarBrands = pd.read_csv(path1)
print(CarBrands)

    <!DOCTYPE html><html><head><meta name="google" content="notranslate"><meta http-equiv="X-UA-Compatible" content="IE=edge;"><style nonce="mqhuGPqBlRLcNbgNZAKoIA">@font-face{font-family:'Roboto';font-style:italic;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu51xIIzc.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:300;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmSU5fBBc9.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:url(//fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:500;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;src:url(//fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf)format('truetype');}</style><meta name="referrer" content="origin"><title>car_brands.csv - Google Drive</title><meta property="og:title" content="car_brands.csv"><meta property="og:type" content="article"><meta property="og:site_name" content="Google Docs"><meta property="og:url" content="https://drive.google.com/file/d/1jLSArDeSsySULKiRtMNV3V3RKuWAUKbD/view?usp=sharing1jLSArDeSsySULKiRtMNV3V3RKuWAUKbD&amp;usp=embed_facebook"><link rel="shortcut icon" href="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Google+Sans:300  \
0                                                 try{
1                                               var ka
2    _.ia=function(){return _.q("Safari")&&!(_.ha()...
3    _.ma=function(a){var b=a.length;if(0<b){for(va...
4    _.ta=function(a){var b;qa?b=a[qa]:b=a.Rb;retur...
..                                                 ...
179                  (function(){var a=_.Td();if(_.E(a
180                     }catch(e){_._DumpException(e)}
181                                    })(this.gbar_);
182                                     // Google Inc.
183  </script><script id="base-js" async type="text...

                                                   400  \
0                                                  NaN
1                                                   wa
2                                                  NaN
3    d=0;d<b;d++)c[d]=a[d];return c}return[]};_.na=...
4    b){qa?a[qa]=b:void 0!==a.Rb?a.Rb=b:Object.defi...
..                                                 ...
179                          18))Rj();else{var b=_.D(a
180                                                NaN
181                                                NaN
182                                                NaN
183  wb" nonce="RnB2Xqp1sjmqiRmafXCMsw"></script></...

                                                   500  \
0                                                  NaN
1                                                   za
2                                                  NaN
3    b){Object.isFrozen(a)||(qa?a[qa]|=b:void 0!==a...
4                                         {Rb:{value:b
..                                                 ...
179              19)||0;window.addEventListener("load"
180                                                NaN
181                                                NaN
182                                                NaN
183                                                NaN

    700" nonce="mqhuGPqBlRLcNbgNZAKoIA"><link rel="stylesheet" href="https://www.gstatic.com/_/apps-fileview/_/ss/k=apps-fileview.v.ZsfbQ_Hjilk.L.X.O/am=AAI/d=0/rs=AO0039sHwTe7S2B7xVQu3Ryhl6C1cYc96w" nonce="mqhuGPqBlRLcNbgNZAKoIA"><script nonce="RnB2Xqp1sjmqiRmafXCMsw">_docs_flag_initialData={"docs-ails":"docs_cold"  \
0                                                  NaN
1                                                   Ea
2                                                  NaN
3                                         {Rb:{value:b
4                                      configurable:!0
..                                                 ...
179                    function(){window.setTimeout(Rj
180                                                NaN
181                                                NaN
182                                                NaN
183                                                NaN

    docs-fwds:"docs_sdf"                    docs-crs:"docs_crs_nfd"  \
0                    NaN                                        NaN
1                     Ga                                         Ha
2                    NaN                                        NaN
3        configurable:!0                                writable:!0
4            writable:!0  enumerable:!1}})};_.va=function(a){_.ra(a
..                   ...                                        ...
179           b)})}})();                                        NaN
180                  NaN                                        NaN
181                  NaN                                        NaN
182                  NaN                                        NaN
183                  NaN                                        NaN

                             docs-l2t:0  \
0                                   NaN
1                                    Ma
2                                   NaN
3    enumerable:!1}}))};_.sa=function(a
4    1);return a};wa=function(a){_.ra(a
..                                  ...
179                                 NaN
180                                 NaN
181                                 NaN
182                                 NaN
183                                 NaN

                                           docs-shdn:0  \
0                                                  NaN
1                                                   Sa
2                                                  NaN
3    b){Object.isExtensible(a)&&(qa?a[qa]&&(a[qa]&=...
4    17);return a};_.xa=function(a){return a?!!(_.t...
..                                                 ...
179                                                NaN
180                                                NaN
181                                                NaN
182                                                NaN
183                                                NaN

                                           docs-tfh:"" info_params:{}  ...  \
0                                                  NaN            NaN  ...
1                                                   Ta             Ua  ...
2                                                  NaN            NaN  ...
3                                                  NaN            NaN  ...
4    16)};za=function(a){return null!==a&&"object"=...            NaN  ...
..                                                 ...            ...  ...
179                                                NaN            NaN  ...
180                                                NaN            NaN  ...
181                                                NaN            NaN  ...
182                                                NaN            NaN  ...
183                                                NaN            NaN  ...

    2.3 5.2  rw 374 0].7 [[null.2 null.199 null.200  \
0   NaN NaN NaN NaN  NaN      NaN      NaN      NaN
1   NaN NaN NaN NaN  NaN      NaN      NaN      NaN
2   NaN NaN NaN NaN  NaN      NaN      NaN      NaN
3   NaN NaN NaN NaN  NaN      NaN      NaN      NaN
4   NaN NaN NaN NaN  NaN      NaN      NaN      NaN
..   ..  ..  ..  ..  ...      ...      ...      ...
179 NaN NaN NaN NaN  NaN      NaN      NaN      NaN
180 NaN NaN NaN NaN  NaN      NaN      NaN      NaN
181 NaN NaN NaN NaN  NaN      NaN      NaN      NaN
182 NaN NaN NaN NaN  NaN      NaN      NaN      NaN
183 NaN NaN NaN NaN  NaN      NaN      NaN      NaN

    https://www.gstatic.com/og/_/js/k=og.qtm.en_US.F9GLv3vJthY.O/rt=j/m=qabr,q_dnp,qapid/exm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/rs=AA2YrTudCw2XotoVCZRHW0V_ffgR5WCCig]]]]  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
179                                                NaN
180                                                NaN
181                                                NaN
182                                                NaN
183                                                NaN

    };this.gbar_=this.gbar_||{};(function(_){var window=this;
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
179                                                NaN
180                                                NaN
181                                                NaN
182                                                NaN
183                                                NaN

[184 rows x 781 columns]

###### **Exercise 13:**
join the cars dataframe with the car brands dataframe.

In [ ]:
# your code here
#result = pd.concat([df1, df4], axis=1)

result = pd.concat([cars, CarBrands], axis = 1)

###### **Bonus:**
create 4 groups (bins) of cars, by Year. We want to explore how cars have evolved decade by decade.

In [ ]:
# your code here
#
Eightys = cars[(cars.Year == 1984) | (cars.Year == 1985) | (cars.Year == 1986) | (cars.Year == 1987)| (cars.Year == 1988)]
Ninties = cars[(cars.Year == 1990) | (cars.Year == 1991)|(cars.Year == 1992) | (cars.Year == 1993)|(cars.Year == 1994) | (cars.Year == 1995)|(cars.Year == 1996) | (cars.Year == 1997)|(cars.Year == 1999)]
twothousands = cars[(cars.Year == 2000) | (cars.Year == 2001) | (cars.Year == 2002) | (cars.Year == 2003)| (cars.Year == 2004) |(cars.Year == 2005) | (cars.Year == 2006) | (cars.Year == 2007) | (cars.Year == 2008)| (cars.Year == 2009)]
twotens = cars[(cars.Year == 2010) | (cars.Year == 2011) | (cars.Year == 2012) | (cars.Year == 2013)| (cars.Year == 2014) |(cars.Year == 2015) | (cars.Year == 2016) | (cars.Year == 2017)]

print(Eightys)
print(Ninties)
print(twothousands)
print(twotens)

#cut_bins = [1980, 1990, 2000, 2010,2020]
#cars['decade'] = pd.cut(x = cars['Year'], bins=cut_bins)
#cars_decade = cars.groupby('decade')
#cars_decade["Fuel Cost/Year"].mean()


#gasEighties = cars.query('Year > 1980 & Year < 1989').mean()
#gasEighties.Fuel_Barrels_per_Year

#bins = [1980, 1990, 2000, 2010, 2020, 2030]
#total_cars['binned_Decade'] = pd.cut(total_cars['Year'], bins)
#print (total_cars)

#year_points = [1980, 1990, 2000, 2010,2020]
#cars['decade'] = pd.cut(x = cars['Year'], bins=year_points, labels=[u'80s', u'90s', u'00s', u'10s'])
#cars_decade = cars.groupby('decade')
#cars_decade.head()


#bins = [0, 1989, 1999, 2009, 2019]
#labels = ['80s', '90s', '00s', '10s']
#cars['bin_d'] = pd.cut(cars['Year'], bins = bins, labels = labels)
#cars

                   Make                Model  Year  EngineDisplacement  \
0            AM General    DJ Po Vehicle 2WD  1984                 2.5
1            AM General     FJ8c Post Office  1984                 4.2
2            AM General  Post Office DJ5 2WD  1985                 2.5
3            AM General  Post Office DJ8 2WD  1985                 4.2
4      ASC Incorporated                  GNX  1987                 3.8
...                 ...                  ...   ...                 ...
35318             Volvo                  780  1988                 2.8
35924              Yugo                   GV  1988                 1.1
35925              Yugo                   GV  1988                 1.3
35928              Yugo               GV/GVX  1987                 1.1
35931              Yugo          Gy/yugo GVX  1986                 1.1

       Cylinders     Transmission         Drivetrain  \
0            4.0  Automatic 3-spd      2-Wheel Drive
1            6.0  Automatic 3-spd      2-Wheel Drive
2            4.0  Automatic 3-spd   Rear-Wheel Drive
3            6.0  Automatic 3-spd   Rear-Wheel Drive
4            6.0  Automatic 4-spd   Rear-Wheel Drive
...          ...              ...                ...
35318        6.0  Automatic 4-spd   Rear-Wheel Drive
35924        4.0     Manual 4-spd  Front-Wheel Drive
35925        4.0     Manual 5-spd  Front-Wheel Drive
35928        4.0     Manual 4-spd  Front-Wheel Drive
35931        4.0     Manual 4-spd  Front-Wheel Drive

                      VehicleClass FuelType  FuelBarrelsPerYear  CityMPG  \
0      Special Purpose Vehicle 2WD  Regular           19.388824       18
1      Special Purpose Vehicle 2WD  Regular           25.354615       13
2      Special Purpose Vehicle 2WD  Regular           20.600625       16
3      Special Purpose Vehicle 2WD  Regular           25.354615       13
4                     Midsize Cars  Premium           20.600625       14
...                            ...      ...                 ...      ...
35318                 Compact Cars  Regular           20.600625       15
35924              Subcompact Cars  Regular           12.677308       24
35925              Subcompact Cars  Regular           13.733750       23
35928              Subcompact Cars  Regular           12.677308       24
35931             Minicompact Cars  Regular           13.184400       22

       HighwayMPG  CombinedMPG  CO2EmissionGramsPerMile  FuelCostPerYear
0              17           17               522.764706             1950
1              13           13               683.615385             2550
2              17           16               555.437500             2100
3              13           13               683.615385             2550
4              21           16               555.437500             2550
...           ...          ...                      ...              ...
35318          19           16               555.437500             2100
35924          29           26               341.807692             1300
35925          27           24               370.291667             1400
35928          29           26               341.807692             1300
35931          29           25               355.480000             1350

[5731 rows x 15 columns]
                        Make              Model  Year  EngineDisplacement  \
5                      Acura        2.2CL/3.0CL  1997                 2.2
6                      Acura        2.2CL/3.0CL  1997                 2.2
7                      Acura        2.2CL/3.0CL  1997                 3.0
11                     Acura        2.3CL/3.0CL  1999                 2.3
12                     Acura        2.3CL/3.0CL  1999                 2.3
...                      ...                ...   ...                 ...
35921  Wallace Environmental          Wetl 850I  1992                 5.0
35922  Wallace Environmental    Wetl Testarossa  1991                 4.9
35923  Wallace Environmental    Wetl Testarossa  1992                 4.9
35926                   Yugo  GV Plus/GV/Cabrio  1990                 1.3
35927                   Yugo  GV Plus/GV/Cabrio  1990                 1.3

       Cylinders     Transmission         Drivetrain      VehicleClass  \
5            4.0  Automatic 4-spd  Front-Wheel Drive   Subcompact Cars
6            4.0     Manual 5-spd  Front-Wheel Drive   Subcompact Cars
7            6.0  Automatic 4-spd  Front-Wheel Drive   Subcompact Cars
11           4.0  Automatic 4-spd  Front-Wheel Drive   Subcompact Cars
12           4.0     Manual 5-spd  Front-Wheel Drive   Subcompact Cars
...          ...              ...                ...               ...
35921       12.0     Manual 6-spd   Rear-Wheel Drive   Subcompact Cars
35922       12.0     Manual 5-spd   Rear-Wheel Drive       Two Seaters
35923       12.0     Manual 5-spd   Rear-Wheel Drive       Two Seaters
35926        4.0     Manual 4-spd  Front-Wheel Drive  Minicompact Cars
35927        4.0     Manual 5-spd  Front-Wheel Drive   Subcompact Cars

      FuelType  FuelBarrelsPerYear  CityMPG  HighwayMPG  CombinedMPG  \
5      Regular           14.982273       20          26           22
6      Regular           13.733750       22          28           24
7      Regular           16.480500       18          26           20
11     Regular           14.982273       20          27           22
12     Regular           13.733750       21          29           24
...        ...                 ...      ...         ...          ...
35921  Premium           25.354615       10          17           13
35922  Premium           29.964545        9          15           11
35923  Premium           29.964545        9          14           11
35926  Regular           14.330870       21          27           23
35927  Regular           13.184400       23          28           25

       CO2EmissionGramsPerMile  FuelCostPerYear
5                   403.954545             1500
6                   370.291667             1400
7                   444.350000             1650
11                  403.954545             1500
12                  370.291667             1400
...                        ...              ...
35921               683.615385             3100
35922               807.909091             3700
35923               807.909091             3700
35926               386.391304             1450
35927               355.480000             1350

[8619 rows x 15 columns]
        Make               Model  Year  EngineDisplacement  Cylinders  \
21     Acura               3.2CL  2001                 3.2        6.0
22     Acura               3.2CL  2002                 3.2        6.0
23     Acura               3.2CL  2003                 3.2        6.0
24     Acura               3.2CL  2003                 3.2        6.0
26     Acura               3.2TL  2000                 3.2        6.0
...      ...                 ...   ...                 ...        ...
35831  Volvo           XC 90 FWD  2009                 3.2        6.0
35940  smart  fortwo convertible  2008                 1.0        3.0
35941  smart  fortwo convertible  2009                 1.0        3.0
35942  smart        fortwo coupe  2008                 1.0        3.0
35943  smart        fortwo coupe  2009                 1.0        3.0

          Transmission         Drivetrain                 VehicleClass  \
21      Automatic (S5)  Front-Wheel Drive                 Compact Cars
22      Automatic (S5)  Front-Wheel Drive                 Compact Cars
23        Manual 6-spd  Front-Wheel Drive                 Compact Cars
24      Automatic (S5)  Front-Wheel Drive                 Compact Cars
26     Automatic 5-spd  Front-Wheel Drive                 Midsize Cars
...                ...                ...                          ...
35831   Automatic (S6)  Front-Wheel Drive  Sport Utility Vehicle - 2WD
35940   Automatic (S5)   Rear-Wheel Drive                  Two Seaters
35941  Automatic (AM5)   Rear-Wheel Drive                  Two Seaters
35942   Automatic (S5)   Rear-Wheel Drive                  Two Seaters
35943  Automatic (AM5)   Rear-Wheel Drive                  Two Seaters

      FuelType  FuelBarrelsPerYear  CityMPG  HighwayMPG  CombinedMPG  \
21     Premium           16.480500       17          27           20
22     Premium           15.695714       17          27           21
23     Premium           16.480500       17          26           20
24     Premium           15.695714       17          27           21
26     Premium           16.480500       17          27           20
...        ...                 ...      ...         ...          ...
35831  Regular           19.388824       14          20           17
35940  Premium            9.155833       33          41           36
35941  Premium            9.155833       33          41           36
35942  Premium            9.155833       33          41           36
35943  Premium            9.155833       33          41           36

       CO2EmissionGramsPerMile  FuelCostPerYear
21                  444.350000             2000
22                  423.190476             1950
23                  444.350000             2000
24                  423.190476             1950
26                  444.350000             2000
...                        ...              ...
35831               522.764706             1950
35940               246.861111             1100
35941               246.861111             1100
35942               246.861111             1100
35943               246.861111             1100

[10585 rows x 15 columns]
        Make         Model  Year  EngineDisplacement  Cylinders  \
39     Acura           ILX  2013                 2.0        4.0
40     Acura           ILX  2013                 2.4        4.0
41     Acura           ILX  2014                 2.0        4.0
42     Acura           ILX  2014                 2.4        4.0
43     Acura           ILX  2015                 2.0        4.0
...      ...           ...   ...                 ...        ...
35947  smart  fortwo coupe  2013                 1.0        3.0
35948  smart  fortwo coupe  2014                 1.0        3.0
35949  smart  fortwo coupe  2015                 1.0        3.0
35950  smart  fortwo coupe  2016                 0.9        3.0
35951  smart  fortwo coupe  2016                 0.9        3.0

         Transmission         Drivetrain  VehicleClass FuelType  \
39     Automatic (S5)  Front-Wheel Drive  Compact Cars  Premium
40       Manual 6-spd  Front-Wheel Drive  Compact Cars  Premium
41     Automatic (S5)  Front-Wheel Drive  Compact Cars  Premium
42       Manual 6-spd  Front-Wheel Drive  Compact Cars  Premium
43     Automatic (S5)  Front-Wheel Drive  Compact Cars  Premium
...               ...                ...           ...      ...
35947       Auto(AM5)   Rear-Wheel Drive   Two Seaters  Premium
35948       Auto(AM5)   Rear-Wheel Drive   Two Seaters  Premium
35949       Auto(AM5)   Rear-Wheel Drive   Two Seaters  Premium
35950       Auto(AM6)   Rear-Wheel Drive   Two Seaters  Premium
35951    Manual 5-spd   Rear-Wheel Drive   Two Seaters  Premium

       FuelBarrelsPerYear  CityMPG  HighwayMPG  CombinedMPG  \
39              11.771786       24          35           28
40              13.184400       22          31           25
41              11.771786       24          35           28
42              13.184400       22          31           25
43              11.771786       24          35           28
...                   ...      ...         ...          ...
35947            9.155833       34          38           36
35948            9.155833       34          38           36
35949            9.155833       34          38           36
35950            9.155833       34          39           36
35951            9.417429       32          39           35

       CO2EmissionGramsPerMile  FuelCostPerYear
39                       318.0             1450
40                       361.0             1600
41                       318.0             1450
42                       361.0             1600
43                       316.0             1450
...                        ...              ...
35947                    244.0             1100
35948                    243.0             1100
35949                    244.0             1100
35950                    246.0             1100
35951                    255.0             1150

[9099 rows x 15 columns]